#!/usr/bin/env racket
#lang racket/base

(require racket/path
         racket/port
         racket/exn
         racket/file
         racket/function
         racket/string
         racket/tcp
         racket/list
         scv-cr
         scv-cr/private/syntax-util
         gtp-util
         basedir)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define port 8182)
(define main
  (vector-ref (current-command-line-arguments) 2))
(define main-dir
  (path-only (path->complete-path (string->path main))))
(define rkt? (curryr path-has-extension? #".rkt"))
(define targets
  (filter rkt? (directory-list main-dir #:build? main-dir)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (targets->name targets benchmark)
  (define bits
    (for/list ([target (in-list targets)])
      (if (module-typed? target) "1" "0")))
  (format "~a_~a" benchmark (string-join bits "")))

(define benchmark-name
  (path->string
   (last (explode-path (simplify-path (build-path main-dir ".."))))))
(define config-dir (targets->name targets benchmark-name))
(define gtp-dir (writable-data-dir #:program "gtp-measure"))
(define dir (build-path gtp-dir "configurations" config-dir))
(make-directory* dir)
(for ([target (in-list targets)])
  (copy-file target (build-path dir (file-name-from-path target)) #t))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define out-port (open-output-string))
(define out
  (with-handlers ([exn:fail? (λ (x) (list 'error (exn->string x)))])
    (parameterize ([current-output-port out-port])
      (optimize targets #:show-blames #t #:ignore-fakes #t))
    (define input-port (open-input-string (get-output-string out-port)))
    (read input-port)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-values (tcp-in tcp-out)
  (tcp-connect "localhost" port))

(if (or (null? out) (pair? out))
    (write out tcp-out)
    (write (list 'unexpected (list (format "~a" out))) tcp-out))

(close-input-port tcp-in)
(close-output-port tcp-out)
(when (and (pair? out) (equal? 'error (car out)))
  (raise-user-error ""))
